import {
  Coffee,
  Music,
  Book,
  Gamepad2,
  Tv,
  Pizza,
  Heart,
  Star,
  Moon,
  Sun,
  Smile,
  Meh,
  Cat,
  Dog,
  Bird,
  Fish,
  Palette,
  Camera,
  Headphones,
  Gift,
  LucideIcon,
} from 'lucide-react-native';

export const iconMap: Record<string, LucideIcon> = {
  Coffee: Coffee,
  Music: Music,
  Book: Book,
  Gamepad2: Gamepad2,
  Tv: Tv,
  Pizza: Pizza,
  Heart: Heart,
  Star: Star,
  Moon: Moon,
  Sun: Sun,
  Smile: Smile,
  Meh: Meh,
  Cat: Cat,
  Dog: Dog,
  Bird: Bird,
  Fish: Fish,
  Palette: Palette,
  Camera: Camera,
  Headphones: Headphones,
  Gift: Gift,
};

export const availableIcons = [
  { name: 'Coffee', icon: Coffee },
  { name: 'Music', icon: Music },
  { name: 'Book', icon: Book },
  { name: 'Gamepad2', icon: Gamepad2 },
  { name: 'Tv', icon: Tv },
  { name: 'Pizza', icon: Pizza },
  { name: 'Heart', icon: Heart },
  { name: 'Star', icon: Star },
  { name: 'Moon', icon: Moon },
  { name: 'Sun', icon: Sun },
  { name: 'Smile', icon: Smile },
  { name: 'Meh', icon: Meh },
  { name: 'Cat', icon: Cat },
  { name: 'Dog', icon: Dog },
  { name: 'Bird', icon: Bird },
  { name: 'Fish', icon: Fish },
  { name: 'Palette', icon: Palette },
  { name: 'Camera', icon: Camera },
  { name: 'Headphones', icon: Headphones },
  { name: 'Gift', icon: Gift },
];

